site_name: MAP-Elites Calorie Burnout Scheduler

nav:
  - Home: index.md

plugins:
  - search
  - mkdocstrings:
      default_handler: python

theme:
  # name: material
  name: mkdocs

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
