class PermissibleRanges:
    MIN_WEIGHT_RANGE, MAX_WEIGHT_RANGE = 40, 500
    MIN_TIME_FRAME, MAX_TIME_FRAME = 1, 48
    MIN_DAILY_EXERCISE_COUNT, MAX_DAILY_EXERCISE_COUNT = 1, 10
    MIN_DAILY_DURATION, MAX_DAILY_DURATION = 15, 8*60
    MIN_BASE_10_SCHEDULE, MAX_BASE_10_SCHEDULE = 1, 127